default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: thuc1991
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ent_dev

test:
  <<: *default
  database: ent_test
#
production:
  <<: *default
  database: ent_production
  username: crm
  password:
